; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File w:\presentations\modern_cpp\factorial.cpp
; Line 19
	mov	eax, 1409286144				; 54000000H
; Line 20
	ret	0
main	ENDP
_TEXT	ENDS
END
